### ISSUE TITLE
How to: get the end of a subscription after it has been canceled

### ISSUE THREAD

**Issue by timkley** [paymill/paymill-php#107]
I have a monthly subscription without `period_of_validity`. If someone cancels his subscription with

```
$subscription->setId('sub_dea86e5c65b2087202e3');
             ->setRemove(false);
```

I get no information about the current period that was booked. If someone subscribes on Sept 1st and cancels on Sept 2nd I have no way to find out, if his subscription is still valid.

Is this by design or is this a bug?

**Comment by Hiroshitai** [comment]
Hi Tim,

this is by design, as we are not calculating the subscription periods, we are triggering a new transaction for each interval. When the subscription is canceled on our side (via API-Call) it is canceled completely and no refund will be given.

If you want to proceed with further questions, please feel free to send us an e-mail to support@paymill.com
