### ISSUE TITLE
PHP Bridge for tokens

### ISSUE THREAD

**Issue by ewgRa** [paymill/paymill-php#113]
I want to cover my code that use paymill by phpunit tests. Problem is that token generated by javascript.

Any plans to ability get token inside php? Maybe at least for sandbox?

**Comment by Plato2013** [comment]
Hi! Bridge does multiple things within the client's browser that must be done there and may not be done within the PHP code on the merchant's server. This is because it is a key component that allows the merchant himself to avoid PCI compliance for his Server / Shop. 

We can think about a stub for testing purposes but that will conflict with the idea of a test system behaving equal to the live system in every aspect. I will take up your suggestion and bring it into the internal discussion.

**Comment by ewgRa** [comment]
Hi! Thanks for quick reply. Would be nice to have this option.

My 5 cents.

Now, for avoid manual testing there is two way: write Selenium (frontend) tests or mock answers from Paymill API.

Sometimes Selenium is not an option.

Mock answers definitely worse than just stub tokens. Because Paymill immediately have transaction answer and no any additional requests goes between client and api - we can avoid mock at all.

Check for example https://github.com/wiseape/payum-paymill repository. Would be nice to cover it by  tests close to payment scenario, but because of tokens this is not possible.
