### ISSUE TITLE
period_of_validity returns null & end_of_period isn't returned at all

### ISSUE THREAD

**Issue by rathesDot** [paymill/paymill-php#119]
Hey guys,

I'm having following problems. I have a subscription that I need details of

```
$subscription = new Paymill\Models\Request\Subscription();
$subscription->setId('sub_dc180b755d10da324864');
$response = $request->getOne($subscription);
```

That's taken from the samples but I am doing the same. But in the resulting Response the `period_of_validity` is null and the `end_of_period` isn't set as an attribute at all ...

Am I missing anything?

_EDIT_: In the merchant center the period_of_validity is shown correctly.

**Comment by christianheidorn** [comment]
Hey,

it seems it's been a while since you encountered this issue. I bumped into it myself and did some digging. I eventually managed to fix it. It seems like it was an oversight by the Paymill team. I've submitted a pull request for this one as it's a minor change but with major impact.

In the meantime you can find my version here: https://github.com/christianheidorn/paymill-php

Regards
Christian
