### ISSUE TITLE
greedy autoload.php 

### ISSUE THREAD

**Issue by lorenzoingrilli** [paymill/paymill-php#88]
i have some trouble using autoload.php together with other frameworks (eg facebook php sdk)
autoload.php seems try to manage out-of-competence classes
to solve, i've changed your implementation to check for "Paymill" namespace before loading a class. It's seems to work right.
below there is my patch. does it do the right thing? if yes, can it be included upstream?

best regards,
Lorenzo

--- my autoload.php ---
<?php

function autoload($className)
{
  $prefix = 'Paymill\';
  $len = strlen($prefix);
  if (strncmp($prefix, $className, $len) !== 0) {
    return;
  }

  $className = ltrim($className, "\");
  $fileName  = '';
  $namespace = '';
  if ($lastNsPos = strripos($className, "\")) {
      $namespace = substr($className, 0, $lastNsPos);
      $className = substr($className, $lastNsPos + 1);
      $fileName  = str_replace("\", DIRECTORY_SEPARATOR, $namespace) . DIRECTORY_SEPARATOR;
  }
  $fileName .= str_replace('_', DIRECTORY_SEPARATOR, $className) . '.php';

  require 'lib/'.$fileName;
}

spl_autoload_register('autoload');

**Comment by ebird2211** [comment]
Hi,

couple of issues here:

1st - don't provide a public function for autoloading - might conflict with other APIs. You can use an autoloading class to encapsulate the whole process (see http://php.net/manual/en/function.spl-autoload-register.php#102180).

2nd - don't grab everything and trigger an error when using "require" - let other autoloaders do their stuff, use "include", prefixed by "if file_exists()".

3rd - you're using strripos (on line #14) incorrectly - this function may return false, or zero as well.
Don't use 

    if ($lastNsPos = strripos($className, '\\')) {

But rather

    if (false !== ($lastNsPos = strripos($className, '\\'=))) {

Best wishes, Ernest

**Comment by nikoloff** [comment]
Hi @ebird2211 
thank you for the feedback, but I have some topics to discuss:

require vs. include: I think it is better to use require in this case since if some of the paymill classes are not loaded for some reason I want the user to be notified with an error about it.

strripos should never return false since the user of the lib should not write new classes inside the lib. Your suggestion here is valid but is a little bit defensive style of programming.

About the public function for autoloading I am not sure how to implement such kind of autoloading.
Can you provide a snippet or pull request for the autoloading script and I can include it in the next version of the wrapper.

10x

**Comment by amlet0** [comment]
to avoid public function, you can use an anonymous function like this:

```php
spl_autoload_register(function($className) {
  $prefix = 'Paymill\\';
  $len = strlen($prefix);
  if (strncmp($prefix, $className, $len) !== 0) {
  return;
  }

  $className = ltrim($className, "\\");
  $fileName = '';
  $namespace = '';
  if ($lastNsPos = strripos($className, "\\")) {
  $namespace = substr($className, 0, $lastNsPos);
  $className = substr($className, $lastNsPos + 1);
  $fileName = str_replace("\\", DIRECTORY_SEPARATOR, $namespace) . DIRECTORY_SEPARATOR;
  }
  $fileName .= str_replace('_', DIRECTORY_SEPARATOR, $className) . '.php';

  require 'lib/'.$fileName;
});
```
